export const typeTranslations = {
  normal: "Normal",
  fire: "Fogo",
  water: "Água",
  grass: "Grama",
  electric: "Elétrico",
  ice: "Gelo",
  fighting: "Lutador",
  poison: "Venenoso",
  ground: "Terra",
  flying: "Voador",
  psychic: "Psíquico",
  bug: "Inseto",
  rock: "Pedra",
  ghost: "Fantasma",
  dragon: "Dragão",
  dark: "Sombrio",
  steel: "Metálico",
  fairy: "Fada",
};

export const typeColors = {
  Normal: "#A8A77A",
  Fogo: "#EE8130",
  Água: "#6390F0",
  Grama: "#7AC74C",
  Elétrico: "#F7D02C",
  Gelo: "#96D9D6",
  Lutador: "#C22E28",
  Venenoso: "#A33EA1",
  Terra: "#E2BF65",
  Voador: "#A98FF3",
  Psíquico: "#F95587",
  Inseto: "#A6B91A",
  Pedra: "#B6A136",
  Fantasma: "#735797",
  Dragão: "#6F35FC",
  Sombrio: "#705746",
  Metálico: "#B7B7CE",
  Fada: "#D685AD",
};
